[package]
name = "updater"
version = "0.1.0"
authors = ["Jochen Kiemes <jochen@kiemes.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12"
curl = "0.4"
reqwest = "0.9"
scraper = "0.10"
chrono = "0.4"
